version: 0.2
 
env:

  variables:

    ECR_REPO_URL: "096961057601.dkr.ecr.us-east-1.amazonaws.com/fhir_validation_repository"
    GIT_BRANCH: "master"
 
phases:

  install:

    runtime-versions:

      docker: 19
 
  pre_build:

    commands:
     - echo "Checking out branch $GIT_BRANCH"
     
      - git checkout $GIT_BRANCH

      - echo "Logging in to Amazon ECR..."

      - aws --version

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
 
  build:

    commands:
      - echo "Building on branch $GIT_BRANCH"

      - echo "Building Docker image..."

      - docker build -t $ECR_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .
 
  post_build:

    commands:

      - echo "Pushing Docker image to ECR..."

      - docker push $ECR_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
 
artifacts:

  files: []

 
